class TestActions:
    TOWAIT = ('Esperar','Wait')
    TOAVOID = ('Evitar', 'Avoid')
    TOACCESS = ('Acessar', 'Access')
    TOCLICK = ('Clicar', 'Click')
    TOIGNORE = ('Ignorar', 'Ignore')
    TOPRESS = ('Pressionar', 'Press')
    TOFILL = ('Preencher', 'Fill')
    TOSELECT = ('Selecionar', 'Select')
    DELAY = ('com delay', 'with delay')